### PR TITLE
New feature: Install tinc via snapd if no package (eg. CentOS8)

### PR DESCRIPTION
**Pull request by planet-winter**
Hi @Steuf

Thanks for your work. Please feel free to take this PR.

I added support for installing tincd via snapd "package". This for OS where no native packages is available, see README
Also fixed private key permissions, see CHANGELOG

Works for me like a charm now. With and without snapd.

Cheers

### CODE REVIEW

**Comment by MatthiasLohr** [comment]
Sure you created the pull request for the right repository? ;)

However, nice to see the further developments of this playbook. However, what about more collaboration and trying to merge the efforts of the most forks?

**Comment by planet-winter** [comment]
Hi @MatthiasLohr 
Huh, I copied the text from the PR for @steuf. I think I forked from "steuf" as It had a feature more.

Sure as of my PR, I am happy to contribute to your repo and keep it in one place.

Works for me, eventough I am not fully happy having to use a snap. However I hope to have saved some work for someone else.

**Comment by Steuf** [comment]
@MatthiasLohr :) I have fork your project for specific usage on Scaleway provider. And no time to test if I have not broken your original playbook. This is for that I haven't send a pull request with my modifications ;)

**Comment by MatthiasLohr** [comment]
This merge request is even overwriting any example, copyright etc, pointing to this repository, where you want to merge it in. This should be changed before any chance to be merged.

**Pull request closed without merging**
